### ISSUE TITLE
第6章 確率分布

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#12]
# 開催日時
2017/08/17 11:30-13:00

# 担当者
@mmyoji 

# 範囲
* 第6章 p.109-132

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料

https://paper.dropbox.com/doc/6-xdlYXzWJj0piFXFan2wvh

# 参考リンク
* 上記資料内に記載

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by nownabe** [comment]
ワイブル分布とは？

**Comment by nownabe** [comment]
## 6.4
![6 4](https://user-images.githubusercontent.com/1286807/29401473-48e21c26-836c-11e7-913e-02334d5ad0b4.JPG)

## 6.5
![img_5982](https://user-images.githubusercontent.com/1286807/29401677-22106520-836d-11e7-95b8-284f82752363.jpg)

![img_5983](https://user-images.githubusercontent.com/1286807/29401687-2db4806e-836d-11e7-9b34-3b058a442df4.jpg)

## 6.6
![img_5984](https://user-images.githubusercontent.com/1286807/29401717-4e5af8b6-836d-11e7-901a-5af2252fc093.jpg)

## 6.7
![img_5985](https://user-images.githubusercontent.com/1286807/29401729-58a4c298-836d-11e7-9ce4-90ca1e4d4243.jpg)

## 6.8
![img_5986](https://user-images.githubusercontent.com/1286807/29401757-6fe88b56-836d-11e7-8f9d-e0d714c3245e.jpg)

## 6.9
![img_5987](https://user-images.githubusercontent.com/1286807/29401771-7b1f2b92-836d-11e7-93f8-d46c8b41a513.jpg)

## 6.10
途中で答えが標準正規分布だったのに気づいた

![img_5988](https://user-images.githubusercontent.com/1286807/29401788-90634074-836d-11e7-8000-1cdcab1ede74.jpg)

**Comment by mmyoji** [comment]
## 6.1

### 二項分布の分散

![ch6-1 1](https://user-images.githubusercontent.com/6119086/29403993-d8fbc552-8374-11e7-8dd3-75e2b6fad3c0.JPG)


### ポアソン分布の分散
![img_5980](https://user-images.githubusercontent.com/1286807/29404493-1d4c9f64-8376-11e7-8038-8e9a3b060ca2.JPG)



## 6.3

![ch6-3](https://user-images.githubusercontent.com/6119086/29404094-2426527c-8375-11e7-91bc-e137df3776a8.JPG)


## 6.4

![ch6-4](https://user-images.githubusercontent.com/6119086/29404106-2beb046c-8375-11e7-9757-b0d196c14a41.JPG)

**Comment by nownabe** [comment]
練習問題の担当

* 6.1 - @mmyoji 
* 6.2 - @takumiumiu 
* 6.3 - @nownabe
* 6.4 - @takumiumiu 
* 6.5 - @nownabe
* 6.6 - @mmyoji 
* 6.7 - @mmyoji 
* 6.8 - @nownabe
* 6.9 - @nownabe
* 6.10 - @nownabe
