### ISSUE TITLE
第7章 多次元の確率分布

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#13]
# 開催日時
2017/08/24 11:30-13:00

# 担当者
@takumiumiu 

# 範囲
* 第7章 p.133-154

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料
https://scrapbox.io/projects/takumi-49622656/invitations/190850617c29c7247df0c1762e858820

# 参考リンク
*

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by nownabe** [comment]
P138のローの証明のQ(t)はどっからでてきた？

**Comment by nownabe** [comment]
# 練習問題
## 7.1
![img_5999](https://user-images.githubusercontent.com/1286807/29560677-c053a284-876d-11e7-8e5f-2ae6cdefcf46.jpg)

## 7.2
(1), (2)
![img_6001](https://user-images.githubusercontent.com/1286807/29560685-cbb9f326-876d-11e7-8ebf-9c05291fd7ba.jpg)

(2)の補足
![img_6002](https://user-images.githubusercontent.com/1286807/29560691-d2b77ee6-876d-11e7-91d4-46b1ab020c5a.jpg)

(3)
![figure_1](https://user-images.githubusercontent.com/1286807/29560699-da2decbe-876d-11e7-9253-ae65774d037c.png)

## 7.3
![img_6003](https://user-images.githubusercontent.com/1286807/29560712-e38cf0fc-876d-11e7-83d4-0dbf37215458.jpg)

## 7.4
![img_6004](https://user-images.githubusercontent.com/1286807/29572045-0b117aa8-8796-11e7-8a5c-8e9e43d12ec8.jpg)

## 7.5
![img_6007](https://user-images.githubusercontent.com/1286807/29572062-149b6b24-8796-11e7-8179-95a998af3188.jpg)

## 7.6
![img_6005](https://user-images.githubusercontent.com/1286807/29572075-1e0f326c-8796-11e7-8746-5e21af665cc1.jpg)

## 7.7
![img_6008](https://user-images.githubusercontent.com/1286807/29625223-1a13eede-8866-11e7-821a-71de3d47aac2.jpg)

## 7.8
![img_6009](https://user-images.githubusercontent.com/1286807/29625233-216c4636-8866-11e7-93be-9eae5dbbcbf3.jpg)

## 7.9
![img_6010](https://user-images.githubusercontent.com/1286807/29625256-2df555e6-8866-11e7-9e7e-5e1c2fef2f3f.jpg)

**Comment by mmyoji** [comment]
# 練習問題

## 7.1

### i.

![img_0636](https://user-images.githubusercontent.com/6119086/29591089-e85d7eb6-87d7-11e7-93e2-aae8e4ffa7c3.jpg)

### ii.

![img_0637](https://user-images.githubusercontent.com/6119086/29591097-f5d4caea-87d7-11e7-88b8-ca50049bed78.jpg)

## 7.2

### i.

![img_0638](https://user-images.githubusercontent.com/6119086/29591103-fea28d42-87d7-11e7-9de7-8fa129f49595.jpg)

### ii.

わからない

### iii.

期待値

![screen shot 2017-08-23 at 7 45 35](https://user-images.githubusercontent.com/6119086/29591124-152e7210-87d8-11e7-8838-173b146e06d3.png)

分散

![screen shot 2017-08-23 at 7 45 53](https://user-images.githubusercontent.com/6119086/29591130-1dd5eee8-87d8-11e7-92bc-0c53708d4a33.png)

## 7.3

WIP

## 7.4

WIP

## 7.5

![img_0639](https://user-images.githubusercontent.com/6119086/29592471-3963a0e0-87df-11e7-8b53-e1c0b1350907.jpg)

![img_0640](https://user-images.githubusercontent.com/6119086/29592473-3be7d070-87df-11e7-85d7-937717a432f6.jpg)

## 7.6

### i.

![img_0642](https://user-images.githubusercontent.com/6119086/29593374-e0f1c436-87e4-11e7-9a8a-ff79dd87027d.jpg)

### ii.

![img_0643](https://user-images.githubusercontent.com/6119086/29593378-e641268e-87e4-11e7-8509-3aed2f9ac967.jpg)

### iii.

わからない

## 7.7

わからない

## 7.8

全然わからない

## 7.9

死っぴ

**Comment by takumiumiu** [comment]
![image uploaded from ios 2](https://user-images.githubusercontent.com/557374/29619586-676cdb60-8856-11e7-8d67-e56cc1b40db4.jpg)

**Comment by nownabe** [comment]
[ユークリッド空間 - Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%BC%E3%82%AF%E3%83%AA%E3%83%83%E3%83%89%E7%A9%BA%E9%96%93)

**Comment by nownabe** [comment]
7.1 @mmyoji 
7.2 (i) @mmyoji (ii) @nownabe
7.3 @takumiumiu 
7.4 @@nownabe
7.5 @takumiumiu 
7.6 @mmyoji 
7.7 @nownabe
7.8 @nownabe
7.9 ( @nownabe )

**Comment by nownabe** [comment]
[相加相乗平均とは？証明~使い方まで全てが分かる記事！｜受験のミカタ](https://juken-mikata.net/how-to/mathematics/additive-geometric-mean.html)

**Comment by nownabe** [comment]
時間内に終わった :tada:
