### ISSUE TITLE
第8章 大数の法則と中心極限定理

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#15]
# 開催日時
2017/09/07 11:30-13:00

# 担当者
@nownabe

# 範囲
* 第8章 p.155-173

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料
https://paper.dropbox.com/doc/8--rs0OrftqRvLPBnRKZVqCx

# 参考リンク
*

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by mmyoji** [comment]
# 練習問題

## 8.1

![img_0649](https://user-images.githubusercontent.com/6119086/30095738-68e7f4de-930f-11e7-84f4-38574f90020b.jpg)

## 8.2 

答えを見てもわからない

## 8.3

わからなかったので答えを見た

![img_0651](https://user-images.githubusercontent.com/6119086/30095741-74ba24a8-930f-11e7-89b7-6e9517921561.jpg)

![img_0652](https://user-images.githubusercontent.com/6119086/30095740-74b37ec8-930f-11e7-804a-852f041c1e6d.jpg)

**Comment by nownabe** [comment]
* 8.1 @mmyoji 
* 8.2 @nownabe
* 8.3 @mmyoji

**Comment by nownabe** [comment]
## 練習問題
### 8.1
![8 1](https://user-images.githubusercontent.com/1286807/30144451-49eaccca-93c6-11e7-810e-cc5456053c44.jpg)

### 8.2
(1)
![8 2](https://user-images.githubusercontent.com/1286807/30144473-662e4cc2-93c6-11e7-9a82-a738cd4e0135.jpg)

(2)
![figure_1](https://user-images.githubusercontent.com/1286807/30144491-838b0f9e-93c6-11e7-9544-61eafdd8e4d4.png)

### 8.3
![8 3](https://user-images.githubusercontent.com/1286807/30144505-8dff88c4-93c6-11e7-8b9c-dc212ef44dec.jpg)
