### ISSUE TITLE
第10章 正規分布からの標本

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#20]
# 開催日時
2017/09/28 11:30-13:00

# 担当者
@nownabe

# 範囲
* 第10章 p.193-211

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料

# 参考リンク
*

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by mmyoji** [comment]
# 練習問題

## 10.1

![img_0660](https://user-images.githubusercontent.com/6119086/30632508-53fcedb2-9e23-11e7-8a42-23d2576aba12.jpg)

## 10.2

![img_0661](https://user-images.githubusercontent.com/6119086/30632509-540367aa-9e23-11e7-9fcd-5c5f67e74fa9.jpg)

## 10.3

i.

![img_0662](https://user-images.githubusercontent.com/6119086/30632510-540d2e0c-9e23-11e7-9d92-263f32b1a16e.jpg)

ii.

??

## 10.4

![279ff694-a332-4f53-ad93-f542036b3b5f](https://user-images.githubusercontent.com/6119086/30945879-a1cb8ee0-a43b-11e7-8405-1c5a797dd029.jpeg)


## 10.5

![44c954d4-f30f-4be3-a3d2-21db7f841d23](https://user-images.githubusercontent.com/6119086/30945889-b2c53386-a43b-11e7-8fdf-47cd54864a37.jpeg)


## 10.6

![c5a069bb-6299-4d19-939f-f6065a9a0a8e](https://user-images.githubusercontent.com/6119086/30945892-bac9281c-a43b-11e7-96ad-fcbf24f196f9.jpeg)


## 10.7

## 10.8

## 10.9

**Comment by nownabe** [comment]
# 練習問題
## 10.1, 10.2
![img_6089](https://user-images.githubusercontent.com/1286807/30911753-c36eb36e-a3c4-11e7-8523-5519d8ad4a95.JPG)

## 10.3
![img_6090](https://user-images.githubusercontent.com/1286807/30911758-ce2abd16-a3c4-11e7-8901-083ccace183b.JPG)

## 10.4, 10.5, 10.6
![img_6091](https://user-images.githubusercontent.com/1286807/30911767-db120e9e-a3c4-11e7-8677-c14a958b9ad1.JPG)

## 10.7
![img_6092](https://user-images.githubusercontent.com/1286807/30911777-e4da644e-a3c4-11e7-9a51-c3f12ef00857.JPG)
![img_6093](https://user-images.githubusercontent.com/1286807/30911780-e85b3f6c-a3c4-11e7-9755-2d3a7c553af9.JPG)

## 10.8
![img_6094](https://user-images.githubusercontent.com/1286807/30911845-292b8ede-a3c5-11e7-93e3-17b296191d31.JPG)

## 10.9
![img_6095](https://user-images.githubusercontent.com/1286807/30911852-2d8c1e1c-a3c5-11e7-81f5-cbd56b099484.JPG)

**Comment by takumiumiu** [comment]
![a](https://user-images.githubusercontent.com/557374/30940188-21bc2e78-a41b-11e7-8cc0-fb9c15f988f0.png)

**Comment by mmyoji** [comment]
* 10.1 @takumiumiu 
* 10.2 @nownabe 
* 10.3 @mmyoji
* 10.4 @takumiumiu 
* 10.5 @takumiumiu 
* 10.6 @mmyoji
* 10.7 @nownabe 
* 10.8 @nownabe 
* 10.9 @nownabe
