### ISSUE TITLE
第11章 推定

### ISSUE THREAD

**Issue by mmyoji** [Wondershake/ml-statistics-intro#21]
# 開催日時
2017/10/05 11:30-13:00

# 担当者
@mmyoji

# 範囲
* 第11章 p.213-232

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料

https://paper.dropbox.com/doc/11-AONSsyvA4gdf5bPfzAIC4?_tk=share_copylink

# 参考リンク
*

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by mmyoji** [comment]
# 練習問題

## 11.1

?

## 11.2

?

## 11.3

![7f674688-3e73-43c5-99bd-08579fa64e3d](https://user-images.githubusercontent.com/6119086/31117787-10f2bcde-a866-11e7-876c-eaf7bd9decec.jpeg)


## 11.4

![8b197eb4-9557-475c-8d4a-768b2f22b50e](https://user-images.githubusercontent.com/6119086/31173379-34f7c444-a942-11e7-91a5-9c345eadac62.jpeg)

## 11.5

母分散が等しいとみなせるのはなぜ...?

https://github.com/Wondershake/ml-statistics-intro/pull/23

## 11.6

https://github.com/Wondershake/ml-statistics-intro/pull/23

## 11.7

![bceb25f1-21ca-4233-9ca7-38d951f7e346](https://user-images.githubusercontent.com/6119086/31173380-351cbe52-a942-11e7-8cee-905d11969872.jpeg)

![8aa62cdd-3d6b-4157-bc77-0603c5073e5e](https://user-images.githubusercontent.com/6119086/31173505-c2d7ae96-a942-11e7-8144-3c447c798fd0.jpeg)

## 11.8, 11.9

![9c616c6c-207c-4f38-9f39-b5368d2e81ac](https://user-images.githubusercontent.com/6119086/31173453-8a191ae0-a942-11e7-8784-b8952738239f.jpeg)

**Comment by nownabe** [comment]
# 練習問題
## 11.1
![2017-10-03 21_42_10](https://user-images.githubusercontent.com/1286807/31125598-c1fd50bc-a883-11e7-9d04-98a7005e2ba6.jpg)

## 11.2
![2017-10-03 22_16_15](https://user-images.githubusercontent.com/1286807/31127041-a6968e38-a888-11e7-889f-9d84645fcd8d.jpg)

## 11.3
![scannable 2017-10-03 22_41_42](https://user-images.githubusercontent.com/1286807/31129344-3a8cc2f0-a88f-11e7-8e83-65ef087ca140.png)

## 11.4
![scannable 2017-10-03 23_03_55](https://user-images.githubusercontent.com/1286807/31129407-6a8a9612-a88f-11e7-8561-4638b0aa5ba3.png)

## 11.5
```bash
$ python 11.5.py
X: [ 7.97  7.66  7.59  8.44  8.05  8.08  8.35  7.77  7.98  8.15]
Y: [ 8.06  8.27  8.45  8.05  8.51  8.14  8.09  8.15  8.16  8.42]
Pooled variance: 0.0528
s: 0.2297
Mean of X: 8.0040
Mean of Y: 8.2300
t = 2.101
[-0.4419, -0.0101]
```

## 11.6
```bash
$ python 11.6.py
X: [25 24 25 26]
Y: [23 18 22 28 17 25 19 16]
a: 0.05
Mean of X: 25.0000
Mean of Y: 21.0000
Variance of X: 0.6667
Variance of Y: 17.7143
nu: 8
t = 2.306
[0.4418, 7.5582]
```

## 11.7
```bash
$ python 11.7.py

(1) 母平均の信頼係数99%の信頼区間を求めよ
東京: [ 21.8  22.4  22.7  24.5  25.9  24.9  24.8  25.3  25.2  24.6]
a: 0.01
東京の標本平均: 24.2100
東京の標本分散: 1.9388
東京の標本偏差: 1.3924
t(9)の上側確率0.5%点: 3.250

式(11.43)より
信頼区間: [22.7790, 25.6410]

(2) 母分散の信頼係数95%の信頼区間を求めよ
χ(9)の上側確率2.5%点: 19.0228
χ(9)の下側確率2.5%点: 2.70039

式(11.45)より
信頼区間: [0.9173, 6.4617]

(3) 東京と大阪の最低気温差の95%信頼区間を作れ
大阪: [ 22.1  25.3  23.3  25.2  25.3  24.9  24.9  24.9  24.9  24. ]
東京 - 大阪: [-0.3 -2.9 -0.6 -0.7  0.6  0.  -0.1  0.4  0.3  0.6]
(東京 - 大阪)の標本平均: -0.2700
(東京 - 大阪)の標本分散: 1.0668
(東京 - 大阪)の標本偏差: 1.0328
t(9)の上側確率2.5%点: 2.262

式(11.43)より
信頼区間: [-1.0088, 0.4688]
```

## 11.8
```bash
$ python 11.8.py
n: 50
p: 0.54
a: 0.05
zの上側確率2.5%点: 1.96
(11.59)式より
信頼区間: [0.4019, 0.6781]
```

## 11.9
```bash
$ python 11.9.py
X: [4 3 5 4 8 2 5 9 3 5]
n: 10
a: 0.01
Zの上側確率0.5%点: 2.58
lambda: 4.8

230ページの式より
信頼区間: [3.0125, 6.5875]
```

**Comment by nownabe** [comment]
# 担当
* 11.1 @nownabe
* 11.2 @nownabe
* 11.3 @mmyoji 
* 11.4 @nownabe
* 11.5 @mmyoji 
* 11.6 @nownabe
* 11.7 @mmyoji 
* 11.8 @nownabe
* 11.9 @mmyoji
