### ISSUE TITLE
第12章 仮説検定

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#26]
# 開催日時
2017/10/12 11:30-13:00

# 担当者
@nownabe

# 範囲
* 第12章 p.233-255

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解く
  * 解答をこのIssueにコメントする
  * ソースコードがあればPushする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料

# 参考リンク
*

# 当日の流れ
90分を想定。
(90分で終わらない場合は範囲を調整する)

* 担当者が内容について解説する
* 練習問題を参加者が順番に解説する
* 適当に議論とか質問とかしつつ進める

**Comment by nownabe** [comment]
# 練習問題
## 12.1
```bash
$ python 12.1.py
測定値: [ 101.1  103.2  102.1   99.2  100.5  101.3   99.7  100.5   98.9  101.4]
帰無仮説 H0: u0 == 100
対立仮説 H1: u0 != 100
有意水準: 0.05
検定統計量 t: 1.890924009250305
上側確率0.025 パーセント点: 2.262

H0は棄却されない
```

## 12.2
```bash
$ python 12.2.py
男: [ 15.4  18.3  16.5  17.4  18.9  17.2  15.   15.7  17.9  16.5]
女: [ 14.2  15.9  16.   14.   17.   13.8  15.2  14.5  15.   14.4]

(1)
帰無仮説 H0: 男の平均賃金 == 女の平均賃金
対立仮説 H1: 男の平均賃金 != 女の平均賃金
有意水準: 0.05
検定統計量 t: 3.606503775109937
上側確率0.025 パーセント点: 2.101

H0は棄却される

(2)
検定統計量 t: 3.606503775109937
n: 17
上側確率0.025 パーセント点: 2.11

H0は棄却される

(3)
帰無仮説 H0: 男の賃金分散 == 女の賃金分散
対立仮説 H1: 男の賃金分散 != 女の賃金分散
有意水準: 0.01
検定統計量 f: 1.5635220125786158
上側確率0.005 パーセント点: 6.541
上側確率0.995 パーセント点: 0.15288182235132242
H0は棄却されない
```

## 12.3
```bash
$ python 12.3.py
帰無仮説 H0: mu0 = 0
対立仮説 H1: mu0 < 0
有意水準: 0.01
検定統計量 t: -1.560009076442849
下側確率0.01 パーセント点: -2.718

H0は棄却されない
```

## 12.4
```bash
$ python 12.4.py
検定統計量: 2.0799999999999996
有意水準: 0.05
上側確率0.05 パーセント点: 11.0705

さいころは正しく作られている
```

## 12.5
```bash
$ python 12.5.py
(1)
円周率:
観測度数: [  8.  12.  11.  10.   8.   9.   8.  12.  14.   8.]
検定統計量: 4.2
等確率か?: True

ネイピア数:
観測度数: [  6.  12.   8.  11.  13.  12.  16.   7.  10.   5.]
検定統計量: 10.8
等確率か?: True

(2)
円周率:
観測度数: [ 116.  103.  103.   93.   97.   94.   95.  101.  106.   93.]
検定統計量: 4.7842157842157835
等確率か?: True

ネイピア数:
観測度数: [  96.   98.  109.  100.   85.   99.   99.  103.  112.  100.]
検定統計量: 4.804195804195804
等確率か?: True
```

## 12.6
```bash
$ python 12.6.py
n: 1469
検定統計量: 1.728463379862236
自由度: 1
有意水準: 0.05
上側確率0.05 パーセント点: 3.84146

関連はない (独立である)
```

## 12.7
```bash
$ python 12.7.py
n: 517
検定統計量: 1.5431365561546417
自由度: 4
有意水準: 0.05
上側確率0.05 パーセント点: 9.48773

関連はない (独立である)
```

## 12.8
### (1)
![scannable 2017-10-11 10_14_19](https://user-images.githubusercontent.com/1286807/31417827-0fa7e0cc-ae6d-11e7-94fa-e901826379ac.jpg)

### (2)
```bash
$ python 12.8.py
補正前: 0.006464124111182934
補正後: 0.23270846800258566
```

## 12.9
```bash
$ python 12.9.py
帰無仮説 H0: p1 == p2
対立仮説 H1: p1 != p2
p1: 0.17647058823529413
p2: 0.07920792079207921
p: 0.12807881773399016
検定統計量 z: 2.073393155507257
有意水準: 0.05
上側確率0.025 パーセント点: 1.96

帰無仮説は棄却される
```

## 12.10
```bash
$ python 12.10.py
(1)
帰無仮説 H0: rho == 0
対立仮説 H0: rho != 0
有意水準: 0.05
標本相関係数 r: 0.6387815655787518
z: -0.26215970212109074
eta: 0.0
検定統計量: -1.7389707341739933
上側確率0.025 パーセント点: 1.96

H0は棄却されない

(2)
帰無仮説 H0: rho == 0.5
対立仮説 H0: rho != 0.5
有意水準: 0.05
標本相関係数 r: 0.6387815655787518
z: -0.26215970212109074
eta: -0.14384103622589045
検定統計量: -0.7848372409395985
上側確率0.025 パーセント点: 1.96

H0は棄却されない
```

**Comment by mmyoji** [comment]
# 練習問題

## 12.1

https://github.com/Wondershake/ml-statistics-intro/pull/24/files

## 12.2

https://github.com/Wondershake/ml-statistics-intro/pull/24/files

## 12.3

https://github.com/Wondershake/ml-statistics-intro/pull/24/files

## 12.4

![5779954c-f705-461b-94b1-0e8791dcd83b](https://user-images.githubusercontent.com/6119086/31431854-cbf618f6-aeaf-11e7-93a5-aa32507ef9b9.jpeg)


## 12.5

## 12.6

https://github.com/Wondershake/ml-statistics-intro/pull/24/files

## 12.7

https://github.com/Wondershake/ml-statistics-intro/pull/24/files

## 12.8

![438b7f56-3bdf-4b17-8b3c-1684621fd8ee](https://user-images.githubusercontent.com/6119086/31431865-d78d4ca2-aeaf-11e7-9f00-d46e30d63007.jpeg)

## 12.9

![5dc61a07-9e69-4567-9993-28bda78c5b12](https://user-images.githubusercontent.com/6119086/31431875-e210bae2-aeaf-11e7-8af5-ddc0a632aa09.jpeg)


## 12.10

?

**Comment by nownabe** [comment]
* 12.1 @mmyoji 
* 12.2 @nownabe
* 12.3 @mmyoji
* 12.4 @mmyoji 
* 12.5 @nownabe
* 12.6 @mmyoji 
* 12.7 @nownabe
* 12.8 @nownabe
* 12.9 @mmyoji
* 12.10 @nownabe
