### ISSUE TITLE
次のテーマ

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#50]
こんな感じでやったらいいんじゃないかと思うけどどう？

1. Pythonではじめる機械学習
2. [Python機械学習プログラミング 達人データサイエンティストによる理論と実践 impress top gearシリーズ | Sebastian Raschka, 株式会社クイープ, 福島 真太朗 | 工学 | Kindleストア | Amazon](https://www.amazon.co.jp/dp/B01HGIPIAK/ref=as_li_ss_tl?ie=UTF8&linkCode=sl1&tag=nownabe0c-22&linkId=85387aa46655c40d6dcb58c21a704579)
    * 本屋で見てきたけど、よさそうだった
    * Pythonではじめる機械学習と被る部分は多そうだが、被ってないところを新しく学び、被ってる所(つまり重要なところ)を復習して実践できるところにもっていく
    * 実践 -> 実践・理論
3. [言語処理のための機械学習入門 (自然言語処理シリーズ) | 高村 大也, 奥村 学 |本 | 通販 | Amazon](https://www.amazon.co.jp/%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92%E5%85%A5%E9%96%80-%E8%87%AA%E7%84%B6%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA-%E9%AB%98%E6%9D%91-%E5%A4%A7%E4%B9%9F/dp/4339027510/ref=as_li_ss_tl?ie=UTF8&qid=1511946595&sr=8-1&keywords=%E8%87%AA%E7%84%B6%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86+%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92&linkCode=sl1&tag=nownabe0c-22&linkId=a5ad207d487d12fe2803cbb39916d848)
    * LOCARIで活かしやすいのはやっぱ自然言語処理
    * 実践 -> 実践・理論 -> 理論
    * 章末問題あり
    * scikit-learnなどのブラックボックスをよりよく使えるように

あと気になったのはこのへん

* [Amazon | Chainer v2による実践深層学習 | 新納 浩幸 | 人工知能](https://www.amazon.co.jp/Chainer-v2%E3%81%AB%E3%82%88%E3%82%8B%E5%AE%9F%E8%B7%B5%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92-%E6%96%B0%E7%B4%8D-%E6%B5%A9%E5%B9%B8/dp/4274221075/ref=as_li_ss_tl?ie=UTF8&qid=1511947132&sr=8-1&keywords=Chainer+v2%E3%81%AB%E3%82%88%E3%82%8B%E5%AE%9F%E8%B7%B5%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92&linkCode=sl1&tag=nownabe0c-22&linkId=0193e7dfe45f51e1dcf35888be9a0eab)
    * 言語処理系のword2vec、RNN、LSTMなんかの話ものってた
* [Amazon | 実践 機械学習システム | Willi Richert, Luis Pedro Coelho, 斎藤 康毅 | ソフトウェア開発・言語](https://www.amazon.co.jp/%E5%AE%9F%E8%B7%B5-%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0-Willi-Richert/dp/4873116988/ref=as_li_ss_tl?s=books&ie=UTF8&qid=1511947214&sr=1-1&keywords=%E5%AE%9F%E8%B7%B5%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0&linkCode=sl1&tag=nownabe0c-22&linkId=b58c9b660932ac6d9c12d71c821bb239)
    * ある程度基礎ができていれば、かなり実践的な例を学べそう
    * トピックモデル、感情分析、レコメンドなど

**Comment by mmyoji** [comment]
めっちゃよさそうです :smile: :raised_hands:

**Comment by nownabe** [comment]
今年の残り1週しかないし、次の本は1月からでいいか

**Comment by nownabe** [comment]
1/8まで冬休みなので、1/11(木)から再開

1章は例のごとく適当に済ませて、11日には2章を今まで通りやってみる。
2章は30ページ弱なのでボリューム的にもよさそう。
2.1〜2.4、2.5〜ぐらいかな

みたいな感じでどうだろう

**Comment by mmyoji** [comment]
totally agree :raising_hand_man:

**Comment by nownabe** [comment]
この本もよさそう

一般化線形モデル入門 原著第2版
http://amzn.to/2D6AXne

> 東京大学出版会の自然科学の統計学、の次に読むと理解を深められる書だと考えている

**Comment by nownabe** [comment]
オンラインの教材も充実してきたのでそれもありかも

* https://www.kaggle.com/learn/overview
* http://weblab.t.u-tokyo.ac.jp/en/deep-learning基礎講座演習コンテンツ-公開ページ/
