### ISSUE TITLE
第4章 データ前処理

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#67]
Python 機械学習プログラミング

# 開催日時
2017/1/25 12:00-13:00

# 範囲
* p.93-122

# 担当
* @mmyoji 4.1-4.4
* @nownabe 4.5-4.6

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 担当範囲を資料にまとめる
* 資料のURLをコメントする
  * URLで参照できれば形式はなんでもOK

# 当日の流れ
60分を想定。
(60分で終わらない場合は範囲を調整する)

* それぞれがまとめた範囲を説明する
* 適当に議論とか質問とかしつつすすめる

**Comment by mmyoji** [comment]
https://gitpitch.com/mmyoji/slides/python-ml-3rd#/

**Comment by nownabe** [comment]
https://nownabe.github.io/slides/20180125-python-ml-ch04/index.html#/

メモ: https://blog.nownabe.com/2018/01/24/1242.html
