### ISSUE TITLE
第4章 確率

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#7]
# 開催日時
2017/07/20

# 範囲
* 第4章 p.67-86

**Comment by nownabe** [comment]
# 練習問題
## 4.1
### i)
1回も出ない確率

```rb
[3] pry(main)> (5.0/6) ** 4
=> 0.4822530864197532
```

### ii)
1回も出ない確率

```rb
[5] pry(main)> (35.0/36) ** 24
=> 0.5085961238690966
```

## 4.2
さいころをx回投げて1回も目の和が12にならない確率は `(35/36)^x`
これが0.1未満であれば良いので、次の方程式を解く。

```
(35/36)^x < 0.1

logをとると

x * log(35/36) < log 0.1

x > 81.7
```

82回投げれば1回は目の和が12になる確率が0.9を越える。

## 4.3
`30C15 = 155,117,520`通り

## 4.4
r人全員の誕生日が異なる確率は

```
(365/365) * (364/365) * (363/365) * ... * ((365 - r + 1) / 365)
```

r人中少なくとも2人が同じ誕生日の確率

```
1 - (365/365) * (364/365) * (363/365) * ... * ((365 - r + 1) / 365)
```

```rb
[11] pry(main)> def p(r)
[11] pry(main)*   1.0 - (1...r).inject(1) { |np, k| np * (1.0 - k / 365.0 ) }
[11] pry(main)* end

[14] pry(main)> rs = [5,10,15,20,21,22,23,24,25,30,35,40,50,60]
=> [5, 10, 15, 20, 21, 22, 23, 24, 25, 30, 35, 40, 50, 60]

[16] pry(main)> rs.each { |r| puts "r = #{r}, Pr = %.4f" % [p(r)] }
r = 5, Pr = 0.0271
r = 10, Pr = 0.1169
r = 15, Pr = 0.2529
r = 20, Pr = 0.4114
r = 21, Pr = 0.4437
r = 22, Pr = 0.4757
r = 23, Pr = 0.5073
r = 24, Pr = 0.5383
r = 25, Pr = 0.5687
r = 30, Pr = 0.7063
r = 35, Pr = 0.8144
r = 40, Pr = 0.8912
r = 50, Pr = 0.9704
r = 60, Pr = 0.9941
```

## 4.5
席をランダムで決めたとき、向かい合う確率は1/3、隣り合う確率は2/3なので妥当ではない。

## 4.6
等しくない。

```
和が9になる組み合わせが出る確率

1 2 6: 6/216
1 3 5: 6/216
1 4 4: 3/216
2 2 5: 3/216
2 3 4: 6/216
3 3 3: 1/216

和が10になる組み合わせが出る確率

1 3 6: 6/216
1 4 5: 6/216
2 2 6: 3/216
2 3 5: 6/216
2 4 4: 3/216
3 3 4: 3/216
```

## 4.7
![img_5950](https://user-images.githubusercontent.com/1286807/28977924-f912fa68-797e-11e7-853c-a2bfec5db650.jpg)

微妙に答えがあってない。。。

**Comment by mmyoji** [comment]
# 練習問題

## 4.1

6の目が少なくとも1回は出る -> 1回も出ないを考える

i) `(5/6) ** 4 = 0.48` なので、少なくとも1回は出る方に賭ける

ii) `(35/36) ** 24 = 0.508` なので、 (6, 6) が出ない方に賭ける

## 4.2

目の和が 12 つまり、 (6, 6) のときのみなので 4.1 と同様に考える

![codecogseqn](https://user-images.githubusercontent.com/6119086/28993782-fb5b4ea8-79f9-11e7-91d3-46d200835e2d.gif)

![codecogseqn 1](https://user-images.githubusercontent.com/6119086/28993829-2a3a01a0-79fb-11e7-8271-a722c126e828.gif)

![codecogseqn 2](https://user-images.githubusercontent.com/6119086/28993843-46138f9a-79fb-11e7-8e77-143369df47eb.gif)

よって n = 82

## 4.3

```python
import math

f = math.factorial
# nCr
# f(n) / f(r) / f(n-r)
f(30) / f(15) / f(30 - 15)
#=> 155,117,520.0 通り
```

## 4.4

証明 -> 知らん！

Pr

```
r =  5, Pr = 0.0271
r = 10, Pr = 0.1169
r = 15, Pr = 0.2529
r = 20, Pr = 0.4114
r = 21, Pr = 0.4437
r = 22, Pr = 0.4757
r = 23, Pr = 0.5073
r = 24, Pr = 0.5383
r = 25, Pr = 0.5687
r = 30, Pr = 0.7063
r = 35, Pr = 0.8144
r = 40, Pr = 0.8912
r = 50, Pr = 0.9704
r = 60, Pr = 0.9941
```

## 4.5

なるほどー

## 4.6

なるほどー

## 4.7

i) は回答見たらわかった

ii) はわからん
