### ISSUE TITLE
第5章 次元削減でデータを圧縮する

### ISSUE THREAD

**Issue by mmyoji** [Wondershake/ml-statistics-intro#70]
Python 機械学習プログラミング

# 開催日時
2017/02/01 12:00-13:00

# 範囲
* p.123-162

# 担当
* @mmyoji 5.1
* @HirokiTerashima0816  5.2
* @nownabe 5.3

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 担当範囲を資料にまとめる
* 資料のURLをコメントする
  * URLで参照できれば形式はなんでもOK

# 当日の流れ
60分を想定。
(60分で終わらない場合は範囲を調整する)

* それぞれがまとめた範囲を説明する
* 適当に議論とか質問とかしつつすすめる

**Comment by nownabe** [comment]
5.3 https://nownabe.github.io/slides/20180201-python-ml-ch05/index.html#/

**Comment by mmyoji** [comment]
https://gitpitch.com/mmyoji/slides/python-ml-4th#/

**Comment by HirokiTerashima0816** [comment]
https://gitpitch.com/HirokiTerashima0816/slides?p=ml-python-5#/
