### ISSUE TITLE
第5章 確率変数

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#8]
# 開催日時
2017/08/10 時間は未定

# 担当者
@nownabe

# 範囲
* 第5章 p.87-108

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 練習問題を解いて解答をこのIssueにコメントする

# 担当者が当日までにやること
参加者が当日までにやることに加え、

* 当日解説するための資料を作る
  * 形式はなんでもいいが、URLで誰でも参照できること
  * 理解できなかったところはわからなかったでOK
* 資料のURLを下に追記する

# 解説資料
https://esa-pages.io/p/sharing/1679/posts/1079/e57bd2be5420051f5e66-slides.html#/

# 参考リンク
*

# 当日の流れ
1時間を想定。
(1時間で終わらない場合は範囲を調整する)

* 担当者が内容、練習問題について説明する
* 適当に議論とか質問とかしつつ進める

**Comment by mmyoji** [comment]
右連続とは？

**Comment by nownabe** [comment]
# 練習問題
## 5.1
### i)
![img_5965](https://user-images.githubusercontent.com/1286807/29154259-246399f4-7dce-11e7-9d8b-d2b705035c4f.jpg)

### iii)
![img_5966](https://user-images.githubusercontent.com/1286807/29154266-2bd7595a-7dce-11e7-8987-06dda7fce051.jpg)
![img_5967](https://user-images.githubusercontent.com/1286807/29154288-4cad6606-7dce-11e7-82df-3306e3457bfe.jpg)


## 5.2
https://github.com/Wondershake/ml-statistics-intro/blob/master/nownabe/ch05/5.2.py

## 5.3
![img_5968](https://user-images.githubusercontent.com/1286807/29154285-47ab645a-7dce-11e7-83b9-cd1457df6f42.jpg)

## 5.4
![img_5969](https://user-images.githubusercontent.com/1286807/29154294-56e59080-7dce-11e7-829e-31864c65b305.jpg)

## 5.5
![img_5971](https://user-images.githubusercontent.com/1286807/29154303-5eb91e94-7dce-11e7-9043-2059a17572dd.jpg)

## 5.6
![img_5972](https://user-images.githubusercontent.com/1286807/29154308-657e9402-7dce-11e7-911f-8df8d93a8fc0.jpg)

## 5.7
スキップ

## 5.8
スキップ
