### ISSUE TITLE
1.3 確率、1.4 連続確率変数

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#82]
言語処理のための機械学習入門

# 開催日時
2018/3/1 12:00-13:00

# 範囲
* p.20-41
    * 1.3
    * 1.4

# 担当
@HirokiTerashima0816 

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 担当範囲を資料にまとめる
* 資料のURLをコメントする
  * URLで参照できれば形式はなんでもOK

# 当日の流れ
60分を想定。
(60分で終わらない場合は範囲を調整する)

* それぞれがまとめた範囲を説明する
* 適当に議論とか質問とかしつつすすめる

**Comment by HirokiTerashima0816** [comment]
https://gitpitch.com/HirokiTerashima0816/slides?p=lp-1.3-1.4#/
