### ISSUE TITLE
1.5 パラメータ推定法

### ISSUE THREAD

**Issue by nownabe** [Wondershake/ml-statistics-intro#85]
言語処理のための機械学習入門

# 開催日時
2018/3/8 12:00-13:00

# 範囲
* p.41-49

# 担当
@mmyoji 

# 参加者が当日までにやること
* 該当範囲を読む
* 疑問点やコメントがあればこのIssueにコメントする
* 担当範囲を資料にまとめる
* 資料のURLをコメントする
  * URLで参照できれば形式はなんでもOK

# 当日の流れ
60分を想定。
(60分で終わらない場合は範囲を調整する)

* それぞれがまとめた範囲を説明する
* 適当に議論とか質問とかしつつすすめる

**Comment by mmyoji** [comment]
https://gitpitch.com/mmyoji/slides/ml-for-nlp-3rd#/
